# Generated by Django 3.2.11 on 2022-01-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='precio',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
