# Generated by Django 3.2.11 on 2022-02-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxapp', '0003_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imagenes'},
        ),
    ]
